# Simply execute "make" in working directory to create executable "hw8"
# Running "make clean" will remove the executable

# PLEASE TEST YOUR MAKEFILE TO ENSURE IT WORKS BEFORE SUBMITTING

all:
	g++ -std=c++11 HW8P5.cpp -o hw8
clean:
	rm hw8
